version: '3.1'

services:
  foxxy:
    build:
      context: .
      dockerfile: Dockerfile_node
    command: /bin/bash -c "yarn && yarn start"
    ports:
      - 4001:4001
    volumes:
      - ./foxxy/:/workspace
      - node_modules:/workspace/node_modules
    depends_on:
      - arangodb
    links:
      - arangodb:arangodb
    networks:
      frontend:

  cms:
    build: .
    #image: solisoft/fasty
    command: /bin/bash -c "cd /var/www && lapis server"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - arangodb
      - foxxy
    links:
      - arangodb:arangodb
    networks:
      frontend:
        ipv4_address: 12.12.0.7

  cms_prod:
    #build: .
    image: solisoft/fasty
    restart: always
    command: /bin/bash -c "cd /var/www && moonc *.moon && moonc **/*.moon && lapis server production"
    ports:
      - 9090:80
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - arangodb
    links:
      - arangodb:arangodb
    networks:
      frontend:
        ipv4_address: 12.12.0.8

  arangodb:
    image: arangodb:latest
    platform: linux/x86_64
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: password
    networks:
      frontend:
        ipv4_address: 12.12.0.6
    ports:
      - 8529:8529
    volumes:
      - arangodb-data:/var/lib/arangodb3
      - arangodb-app:/var/lib/arangodb3-apps

  nginx:
    image: nginx:1.17.3
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    links:
      - cms
    networks:
      frontend:
        ipv4_address: 12.12.0.10

volumes:
  arangodb-data:
  arangodb-app:
  node_modules:
  node_modules_resize:

networks:
  frontend:
    ipam:
      config:
        - subnet: 12.12.0.0/24
